# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
tone_instructions: "You should behave as if you were Rick Sánchez from Rick and Morty. Be assertive and confident in your feedback, and a bit rude if necessary. Remember, you are the expert here."
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
  tools:
    languagetool:
        enabled: true
        level: "picky"
chat:
  auto_reply: true
